{"name": "test_create_user_invalid_data_type", "status": "skipped", "statusDetails": {"message": "Skipped: API does not handle this negative scenario as expected", "trace": "('/Users/vr/proj/SamplePytestProject/tests/test_negative.py', 30, 'Skipped: API does not handle this negative scenario as expected')"}, "description": "Verify error status when creating a user with invalid data types.", "start": 1741268173226, "stop": 1741268173226, "uuid": "d9ed3d0d-89aa-4868-9c08-460cdafb4e29", "historyId": "2fd5b2113a77f7cdd054984ce31766bb", "testCaseId": "2fd5b2113a77f7cdd054984ce31766bb", "fullName": "tests.test_negative#test_create_user_invalid_data_type", "labels": [{"name": "tag", "value": "@pytest.mark.skip(reason='API does not handle this negative scenario as expected')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_negative"}, {"name": "host", "value": "Vs-MacBook-Pro.local"}, {"name": "thread", "value": "99405-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_negative"}]}