{"uuid": "6125c6cb-8f02-4094-8e89-7abe6a52d213", "children": ["9dba1d41-f4db-4f3a-8ef9-2dd6c954c407"], "befores": [{"name": "setup_wiremock", "status": "broken", "statusDetails": {"message": "_pytest.outcomes.Exit: Docker is not running. Please start Docker and retry.\n", "trace": "  File \"/Users/vr/proj/SamplePytestProject/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/vr/proj/SamplePytestProject/.venv/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/vr/proj/SamplePytestProject/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/vr/proj/SamplePytestProject/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/vr/proj/SamplePytestProject/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/vr/proj/SamplePytestProject/tests/conftest.py\", line 29, in setup_wiremock\n    pytest.exit(\"Docker is not running. Please start Docker and retry.\")\n  File \"/Users/vr/proj/SamplePytestProject/.venv/lib/python3.9/site-packages/_pytest/outcomes.py\", line 123, in exit\n    raise Exit(reason, returncode)\n"}, "start": 1739782451763, "stop": 1739782452075}], "start": 1739782451763, "stop": 1739782452270}